#!/bin/bash

#Remove prohibited files
sudo apt remove ophcrack
sudo apt remove wireshark -y
sudo apt-get autoremove -y
sudo apt remove nmap
sudo apt remove nessus
sudo apt remove kismet
sudo apt remove metasploit
sudo apt remove aircrack-ng
sudo apt remove openvas
sudo apt remove sqlmap
sudo apt remove zenmap
sudo apt remove rainbow-crack
sudo apt remove ccleaner

#Check for prohibeted software, as well as stops prohibited software from running.
systemctl list-units --type=service --state=active
sudo systemctl stop nginx 
sudo systemcrl disable nginx


# Enable firewall

#installs firewall
sudo apt install ufw

#gives firewall status
sudo ufw status verbose
sudo ufw status >> firewall-status.txt

#configures settings
sudo ufw default deny incoming
sudo ufw enable

#allows services
sudo ufw sudo ufw allow ssh
sudo ufw allow 4422/tcp

#denies specific ports
enable    #firewall on
sudo ufw deny 23    #block Telnet
sudo ufw deny 515   #block printer port
sudo ufw allow log 22/tcp
sudo ufw allow 139
sudo ufw allow 445
sudo ufw allow 137
sudo ufw allow 138
sudo ufw deny 21
sudo ufw deny cups

#disables these two services
sudo apt-get purge -y cups
sudo apt-get purge -y bluetooth


#start Open SSH at boot
sudo update-rc.d ssh enable
/etc/rc3.d/


#deletes all media files

find /home -name '*.mp3' -type f -delete
    	find /home -name '*.mov' -type f -delete
    	find /home -name '*.mp4' -type f -delete
    	find /home -name '*.avi' -type f -delete
    	find /home -name '*.mpg' -type f -delete
    	find /home -name '*.mpeg' -type f -delete
    	find /home -name '*.flac' -type f -delete
    	find /home -name '*.m4a' -type f -delete
    	find /home -name '*.flv' -type f -delete
    	find /home -name '*.ogg' -type f -delete
    	find /home -name '*.gif' -type f -delete
    	find /home -name '*.png' -type f -delete
    	find /home -name '*.jpg' -type f -delete
 
#updates system
 sudo apt update
 sudo apt upgrade
 sudo reboot

